baseURL = 'https://non-neutralzero.github.io/docs/'
languageCode = 'en-us'
title = 'Docs - NonNeutralZero'
theme = 'hugo-book'


[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/Non-NeutralZero"
  weight = 10

[[menu.after]]
  name = "NonNeutralZero"
  url = "https://nonneutralzero.com"
  weight = 20

[params]
  BookTheme = 'light'
  BookRepo = 'https://github.com//Non-NeutralZero/docs'
  BookComments = false
  BookSection = 'docs'
