baseURL = 'https://non-neutralzero.github.io/docs/'
languageCode = 'en-us'
title = 'Docs - NonNeutralZero'
theme = 'hugo-book'

# Syntax highlighting
pygmentsCodeFences = true 
pygmentsUseClasses = false  
pygmentsStyle = "nord"  

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/Non-NeutralZero"
  weight = 10

[[menu.after]]
  name = "NonNeutralZero"
  url = "https://nonneutralzero.com"
  weight = 20

[[menu.after]]
  name = "Linktr"
  url = "https://linktr.ee/nonneutralzero"
  weight = 30

[params]
  BookTheme = 'light'
  BookRepo = 'https://github.com//Non-NeutralZero/docs'
  BookSection = 'docs'
  BookCommitPath = 'commit'

[params.extra]
copyright = "© 2023. NonNeutralZero."
poweredby = true