baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Docs - NonNeutralZero'

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/Non-NeutralZero"
  weight = 10

[[menu.after]]
  name = "NonNeutralZero"
  url = "https://nonneutralzero.com"
  weight = 20

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'

  #BookLogo = 'favicon-elephant-192x192.png'

